//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChatBoard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Board
    {
        public Board()
        {
            this.LoggedInUsers = new HashSet<LoggedInUser>();
            this.Messages = new HashSet<Message>();
        }
    
        public string BoardId { get; set; }
        public string Topic { get; set; }
        public string Description { get; set; }
        public string Tags { get; set; }
        public string OwnerId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public string Status { get; set; }
    
        public virtual ICollection<LoggedInUser> LoggedInUsers { get; set; }
        public virtual ICollection<Message> Messages { get; set; }
    }
}
